# -*- coding: utf-8 -*-
"""Hotels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-mDbEkoyjLF5h4vTsIXFqsKRvB0_DxK

# **Hotels Data Analysis**
"""

# Commented out IPython magic to ensure Python compatibility.
#Importing Liberaries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline
import plotly.graph_objects as go
import plotly.express as px

"""**Explanatory Data Analysis**"""

#Importing Hotels Dataset
df = pd.read_csv('hotels.csv')
df

# Displaying The First 5 Rows of The Data
df.head()

# Displaying The Last 5 Rows of The Data
df.tail()

# Displaying The Number of Rows and Columns of The Data
df.shape

# Displaying Informations of The Data
df.info()

# Displaying Data Types of The Data
df.dtypes

# Displaying Columns of The Data
df.columns

# Displaying Discription of The Data
df.describe()

"""**Data Cleaning**"""

df['is_canceled'] = df['is_canceled'].replace([0,1],['Not Cancelled','Cancelled'])

df['arrival_date_month'] = df['arrival_date_month'].replace(
    ['January','February','March','April','May','June','July','August','September','October','November','December'],
    ['Jan' , 'Feb' , 'Mar' , 'Apr' , 'May' , 'Jun' , 'Jul' , 'Aug' , 'Sep' , 'Oct' , 'Nov' , 'Dec'])

df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

df.drop(['agent','company'],axis=1,inplace=True)

df.dropna(inplace=True)

for col in df.columns:
  if df[col].dtype == 'object':
    print(col,df[col].unique())
    print('-'*50)
    print()

"""**Data Visualization**"""

reservation_status_percentages = df['reservation_status'].value_counts(normalize=True) * 100
display(pd.DataFrame(reservation_status_percentages).style.format('{:.2f}%'))

Cancelation_Status = df['is_canceled'].value_counts(normalize=True) * 100
display(pd.DataFrame(Cancelation_Status).style.format('{:.2f}%'))

plt.figure(figsize=(12,5))
sns.barplot(x=Cancelation_Status.index,y=Cancelation_Status.values,palette='rocket')
plt.title('Cancelation Status Percentage')
plt.xlabel('Cancelation Status')
plt.show()

Hotel_Cancelation_Status = df['is_canceled'].groupby(df['hotel']).value_counts(normalize=True)*100
display(pd.DataFrame(Hotel_Cancelation_Status).style.format('{:.2f}%'))

plt.figure(figsize=(12,5))
sns.barplot(x=Hotel_Cancelation_Status.index.get_level_values(0), y=Hotel_Cancelation_Status.values, hue=Hotel_Cancelation_Status.index.get_level_values(1), palette='rocket')
plt.title('Cancelation Status by Hotel Type')
plt.xlabel('Hotel Type')
plt.show()

df['arrival_date_month'].groupby(df['is_canceled'].value_counts(normalize=True))

monthly_cancellation_rates = df.groupby('arrival_date_month')['is_canceled'].value_counts(normalize=True).unstack()
display(pd.DataFrame(monthly_cancellation_rates.sort_values(by='Cancelled' , ascending=False)['Cancelled']).style.format('{:.2%}'))

plt.figure(figsize=(14, 7))

# Define the chronological order of months
month_order = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

# Reindex the monthly_cancellation_rates DataFrame to ensure chronological order
monthly_cancellation_rates_ordered = monthly_cancellation_rates.reindex(month_order)

# Plot 'Cancelled' rates
sns.lineplot(x=monthly_cancellation_rates_ordered.index, y=monthly_cancellation_rates_ordered['Cancelled'], label='Cancelled', marker='o', color='red')

plt.title('Monthly Booking Status Rates', fontsize=16)
plt.xlabel('Month', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7) # Add a grid for better readability
plt.legend(title='Status', fontsize=10) # Add a legend
plt.xticks(rotation=45) # Rotate x-axis labels for better readability
plt.tight_layout() # Adjust layout to prevent labels from being cut off
plt.show()

Year_Cancelation_Status = df['is_canceled'].groupby(df['arrival_date_year'].astype(int)).value_counts(normalize=True).unstack()
display(pd.DataFrame(Year_Cancelation_Status.sort_values(by = 'Cancelled' , ascending=False)['Cancelled']).style.format('{:.2%}'))

plt.figure(figsize=(10, 6))

sns.lineplot(x=Year_Cancelation_Status.index, y=Year_Cancelation_Status['Cancelled'], label='Cancelled', marker='o', color='red')

plt.title('Yearly Booking Status Rates', fontsize=16)
plt.xlabel('Year', fontsize=12)
plt.xticks(Year_Cancelation_Status.index)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='Status', fontsize=10)
plt.tight_layout()
plt.show()

Year_Month_Cancelation_Status = df['is_canceled'].groupby([df['arrival_date_year'].astype(int), df['arrival_date_month']]).value_counts(normalize=True).unstack()

# Convert 'arrival_date_month' to a categorical type with ordered months for chronological sorting
Year_Month_Cancelation_Status.index = pd.MultiIndex.from_arrays([
    Year_Month_Cancelation_Status.index.get_level_values('arrival_date_year'),
    pd.Categorical(Year_Month_Cancelation_Status.index.get_level_values('arrival_date_month'), categories=month_order, ordered=True)
], names=['arrival_date_year', 'arrival_date_month'])

# Sort the index by year and then by the chronologically ordered month
Year_Month_Cancelation_Status_chronological = Year_Month_Cancelation_Status.sort_index()

display(pd.DataFrame(Year_Month_Cancelation_Status_chronological['Cancelled']).style.format('{:.2%}'))

df_plot = Year_Month_Cancelation_Status_chronological.reset_index()
print(df_plot.head())

plt.figure(figsize=(14, 7))
sns.lineplot(data=df_plot, x='arrival_date_month', y='Cancelled', hue='arrival_date_year', marker='o', palette='deep')
plt.title('Monthly Cancellation Rates by Year', fontsize=16)
plt.xlabel('Month', fontsize=12)
plt.ylabel('Cancellation Rate', fontsize=12)
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='Year', fontsize=10)
plt.tight_layout()
plt.show()

Market_Segment_Cancellation = df.groupby('market_segment')['is_canceled'].value_counts(normalize=True).unstack()
display(pd.DataFrame(Market_Segment_Cancellation.sort_values(by='Cancelled' , ascending=False)['Cancelled']).style.format('{:.2%}'))

plt.figure(figsize=(12,5))
sns.barplot(y=Market_Segment_Cancellation.index,x=Market_Segment_Cancellation['Cancelled'],palette='rocket')
plt.title('Cancelation Status by Market Segment')
plt.xlabel('Market Segment')
plt.show()

Deposit_Type_Cancellation = df.groupby('deposit_type')['is_canceled'].value_counts(normalize=True).unstack()
display(pd.DataFrame(Deposit_Type_Cancellation.sort_values(by='Cancelled' , ascending=False)['Cancelled']).style.format('{:.2%}'))

plt.figure(figsize=(6,6))
plt.pie(Deposit_Type_Cancellation['Cancelled'], labels=Deposit_Type_Cancellation.index, autopct='%1.1f%%', colors=sns.color_palette('rocket'))
plt.title('Cancellation Status by Deposit Type')
plt.show()

Country_Cancellation_Rates = df.groupby('country')['is_canceled'].value_counts(normalize=True).unstack().fillna(0).head()
display(pd.DataFrame(Country_Cancellation_Rates.sort_values(by='Cancelled', ascending=False)['Cancelled']).style.format('{:.2%}'))

Customer_Cancellation = df.groupby('customer_type')['is_canceled'].value_counts(normalize=True).unstack()
display(pd.DataFrame(Customer_Cancellation.sort_values(by='Cancelled' , ascending=False)['Cancelled']).style.format('{:.2%}'))

plt.figure(figsize=(10,6))
sns.barplot(x=Customer_Cancellation.index,y=Customer_Cancellation['Cancelled'],palette='rocket')
plt.title('Cancelation Status by Customer Type')
plt.xlabel('Customer Type')
plt.show()

Distribution_Channel_Cancellation = df.groupby('distribution_channel')['is_canceled'].value_counts(normalize=True).unstack().fillna(0)
display(pd.DataFrame(Distribution_Channel_Cancellation.sort_values(by='Cancelled' , ascending=False)['Cancelled']).style.format('{:.2%}'))

Reserved_Room_Cancellation = df.groupby('reserved_room_type')['is_canceled'].value_counts(normalize=True).unstack()
display(pd.DataFrame(Reserved_Room_Cancellation.sort_values(by='Cancelled' , ascending=False)['Cancelled']).style.format('{:.2%}'))

df['room_changed'] = df['reserved_room_type'] != df['assigned_room_type']
percentage_room_changed = df['room_changed'].mean() * 100
print(f"Percentage of bookings where room type changed: {percentage_room_changed:.2f}%")

room_type_crosstab = pd.crosstab(df['reserved_room_type'], df['assigned_room_type'])
print("\nCross-tabulation of Reserved vs. Assigned Room Types:")
display(room_type_crosstab)

plt.figure(figsize=(12, 8))
sns.heatmap(room_type_crosstab.apply(lambda x: x / x.sum(), axis=1), annot=True, fmt='.2%', cmap='viridis', linewidths=.5)
plt.title('Percentage Distribution of Assigned Room Types by Reserved Room Type')
plt.xlabel('Assigned Room Type')
plt.ylabel('Reserved Room Type')
plt.show()

df['room_mismatch'] = (df['reserved_room_type'] != df['assigned_room_type']).astype(int)

Mismatch_Cancellation = df.groupby('room_mismatch')['is_canceled'].value_counts(normalize=True).unstack() * 100
display(Mismatch_Cancellation.style.format('{:.2f}%'))

plt.figure(figsize=(12,5))
sns.barplot(x=Mismatch_Cancellation.index, y=Mismatch_Cancellation['Cancelled'])
plt.title('Cancellation Rate by Room Match vs Mismatch')
plt.xlabel('Room Mismatch (0 = Match, 1 = Mismatch)')
plt.ylabel('Cancellation Rate (%)')
plt.show()

df_cancelled = df[df['is_canceled'] == 'Cancelled']
px.box(data_frame=df_cancelled, x='reserved_room_type' , y = 'adr' , color ='hotel' , template='plotly_dark')

df['arrival_date_month'] = pd.Categorical(df['arrival_date_month'], categories=month_order, ordered=True)

plt.figure(figsize=(14, 7))
sns.lineplot(data=df, x='arrival_date_month', y='adr', hue='hotel', marker='o')
plt.title('Average Daily Rate (ADR) by Month and Hotel Type', fontsize=16)
plt.xlabel('Arrival Month', fontsize=12)
plt.ylabel('Average Daily Rate (ADR)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()